### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by Latada** [Latada/practice-todo-app#1]
### 만들고자 하는 기능이 무엇인가요?
일정 관리하는 어플 

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [x] Todo 추가하는 기능 [C]
2. [x] Todo 렌더링 하는 기능 [R]
3. [ ] Todo 수정하는 기능 [U]
4. [x] Todo 삭제하는 기능 [D]

### 예상 작업 시간
일주일
